name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Docker
        run: |
          docker --version
      
      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin <aws-account-id>.dkr.ecr.<region>.amazonaws.com
      
      - name: Build Docker Image
        run: |
          docker build -t my-lambda-container .
      
      - name: Tag and Push Image to ECR
        run: |
          docker tag my-lambda-container:latest <aws-account-id>.dkr.ecr.<region>.amazonaws.com/my-lambda-container:latest
          docker push <aws-account-id>.dkr.ecr.<region>.amazonaws.com/my-lambda-container:latest

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code --function-name my-lambda-function --image-uri <aws-account-id>.dkr.ecr.<region>.amazonaws.com/my-lambda-container:latest
